name: Build
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Yarn packages
        run: yarn install
      - name: Build the app
        run: yarn make
        timeout-minutes: 20
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: out/make/*
